version: '3'

services:
  jenkins-master:
    container_name: jenkins-master
    build: ./jenkins-master-swarm
    #image: martinq/jenkins-master-swarm
    ports:
      - 8080:8080
      - 50000:50000
    volumes:
      - /srv/jenkins-master:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock

  docker-proxy:
    container_name: docker-proxy
    build: ./docker-proxy
    #image: martinq/docker-proxy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  jenkins-slave:
    container_name: jenkins-slave
    build: ./jenkins-slave-swarm
    #image: martinq/jenkins-swarm-client
    environment:
      - LABELS=docker
      - EXECUTORS=3
      - FSROOT=/var/jenkins_home
    volumes:
      - /srv/jenkins-slave:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    command: "-master http://jenkins-master:8080/ -name docker-slave -username admin -password admin"
